CREATE TABLE IF NOT EXISTS entries (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  entry_type INTEGER NOT NULL,
  user TEXT NOT NULL
);